### ISSUE TITLE
Main branch:do not work well on my desktop

### ISSUE THREAD

**Issue by yoxchen1** [guanxiaotongyz/Mobile-spotAdviosr#8]
After npm start with main branch:
It just shown:
<img width="1138" alt="image" src="https://user-images.githubusercontent.com/98132024/230736836-b0382ed1-7f31-4722-889a-6d3733f7622d.png">
Here is the solution I searched:
https://github.com/facebook/react-native/issues/34837
But still cant work for me.

**Comment by guanxiaotongyz** [comment]
resolved
